// Generated by CoffeeScript 1.7.1
(function() {
  var func, http, server, url;

  http = require('http');

  url = require('url');

  func = function(request, response) {
    var input, numInput, numOutput, params, parser;
    response.writeHead(200, {
      'Content-Type': "text/plain"
    });
    parser = url.parse(request.url, true);
    params = parser.query;
    input = params.number;
    numInput = Number(input);
    console.log(numInput);
    numOutput = Number(Math.random() * numInput);
    numOutput = numOutput.toFixed(0);
    response.write(numOutput);
    response.end;
    console.log('finish');
  };

  server = http.createServer(func);

  server.listen(82);

  console.log('Running...');

}).call(this);
